# Generated by Django 4.2.4 on 2023-09-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='team',
            name='admin_id',
            field=models.ManyToManyField(related_name='Admin', to='Backend.user'),
        ),
    ]
