# Generated by Django 4.2.4 on 2023-10-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_moduser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='notAllowedTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='allowed',
        ),
        migrations.AddField(
            model_name='amenity',
            name='not_allowed',
            field=models.ManyToManyField(to='Backend.notallowedtimes'),
        ),
    ]
