# Generated by Django 4.2.4 on 2023-10-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_remove_amenity_freeslots_amenity_freeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='freeslots',
        ),
        migrations.AddField(
            model_name='amenity',
            name='freeslots',
            field=models.ManyToManyField(to='Backend.freeslots'),
        ),
    ]
