# Generated by Django 4.2.4 on 2023-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_amenity_end_time_amenity_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbooking',
            name='duration_of_slot',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='individualbooking',
            name='duration_of_slot',
            field=models.IntegerField(default=60),
        ),
    ]
