# Generated by Django 4.2.4 on 2023-10-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_groupbooking_time_of_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='amenity_id',
            new_name='amenity',
        ),
    ]
