# Generated by Django 4.2.4 on 2023-10-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_remove_amenity_freeslots_amenity_freeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='freeslots',
        ),
        migrations.AddField(
            model_name='freeslots',
            name='amenity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.amenity'),
        ),
    ]
