# Generated by Django 4.2.4 on 2023-10-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_rename_amenity_id_event_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
