# Generated by Django 4.2.4 on 2023-10-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_numbers_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(to='Backend.team'),
        ),
    ]
