# Generated by Django 4.2.4 on 2023-11-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_user_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='credits',
            field=models.IntegerField(default=5),
        ),
    ]
