# Generated by Django 4.2.4 on 2023-09-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_groupbooking_duration_of_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbooking',
            name='duration_of_slot',
            field=models.DurationField(default=None),
        ),
        migrations.AlterField(
            model_name='individualbooking',
            name='duration_of_slot',
            field=models.DurationField(default=None),
        ),
    ]
