# Generated by Django 4.2.4 on 2023-11-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_alter_individualbooking_timestamp_of_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbooking',
            name='timestamp_of_booking',
            field=models.DateTimeField(),
        ),
    ]
