# Generated by Django 4.2.4 on 2023-09-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_alter_groupbooking_duration_of_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupbooking',
            old_name='duration_of_slot',
            new_name='duration_of_booking',
        ),
        migrations.RenameField(
            model_name='individualbooking',
            old_name='duration_of_slot',
            new_name='duration_of_booking',
        ),
    ]
