# Generated by Django 4.2.4 on 2023-09-30 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_rename_duration_of_slot_groupbooking_duration_of_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.time(8, 0))),
                ('end_time', models.DateTimeField(default=datetime.time(22, 0))),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='freeslots',
            field=models.ManyToManyField(to='Backend.freeslot'),
        ),
    ]
