# Generated by Django 4.2.4 on 2023-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_freeslot_amenity_freeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='freeslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='freeslot',
            name='slot',
            field=models.IntegerField(default=1),
        ),
    ]
