# Generated by Django 4.2.4 on 2023-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_remove_freeslot_end_time_remove_freeslot_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeslot',
            name='slot',
            field=models.IntegerField(default=2),
        ),
    ]
