# Generated by Django 4.2.4 on 2023-09-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_alter_freeslot_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='freeslots',
        ),
        migrations.AlterField(
            model_name='freeslot',
            name='slot',
            field=models.IntegerField(default=1),
        ),
    ]
