# Generated by Django 4.2.4 on 2023-09-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_remove_amenity_freeslots_alter_freeslot_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='FreeSlot',
        ),
    ]
