# Generated by Django 4.2.4 on 2023-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_numbers_delete_freeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='freeslots',
            field=models.ManyToManyField(to='Backend.numbers'),
        ),
    ]
