# Generated by Django 4.2.4 on 2023-10-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_amenity_freeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbers',
            name='slot',
        ),
        migrations.AlterField(
            model_name='numbers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
