# Generated by Django 4.2.4 on 2023-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_remove_numbers_slot_alter_numbers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbooking',
            name='time_of_slot',
            field=models.TimeField(),
        ),
    ]
