# Generated by Django 4.2.4 on 2023-10-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_alter_individualbooking_time_of_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbooking',
            name='name_of_slot',
        ),
    ]
