# Generated by Django 4.2.4 on 2023-10-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0022_remove_individualbooking_name_of_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupbooking',
            old_name='amenity_id',
            new_name='amenity',
        ),
        migrations.RenameField(
            model_name='individualbooking',
            old_name='amenity_id',
            new_name='amenity',
        ),
    ]
