# Generated by Django 4.2.4 on 2023-10-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_rename_amenity_id_groupbooking_amenity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupbooking',
            old_name='booker_id',
            new_name='booker',
        ),
        migrations.RenameField(
            model_name='individualbooking',
            old_name='booker_id',
            new_name='booker',
        ),
    ]
